# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=y

# RTT logging
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y

CONFIG_CPP=y
CONFIG_GLIBCXX_LIBCPP=y

# === NUS ===
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y
CONFIG_BT_CENTRAL=y
# === NUS ===

# === to address an error with threaded code ===
CONFIG_STATIC_INIT_GNU=y

# to enable NUS
CONFIG_SERIAL=y
CONFIG_NRFX_UARTE0=n
CONFIG_UART_ASYNC_API=y
CONFIG_UART_CONSOLE=y 
CONFIG_UART_MCUMGR=y 

CONFIG_RING_BUFFER=y

##==================

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_STDOUT_CONSOLE=n

CONFIG_USE_SEGGER_RTT=y
CONFIG_PRINTK=y 
CONFIG_LOG=y 
CONFIG_LOG_BACKEND_RTT=y



# === to address an error with threaded code ===
CONFIG_STATIC_INIT_GNU=y



CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y